config/routes.rb
KnowledgeBase::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => 'registrations', :sessions => "sessions"}

  # Administration
  namespace :admin do
    resources :facts, :only => [:index, :update, :destroy]
    resources :categories, :only => [:index, :create, :update, :destroy]

    root :to => "overview#index"
  end

  resources :facts, :except => :index do
    get :autocomplete_tag_name, :on => :collection
    resources :comments
  end

  resources :tags, :only => [:create, :destroy] do
    collection do
      get 'add'
    end
  end

  resources :authentications, :only => :destroy
  match '/auth/:provider/callback' => 'authentications#create'

  match "/feed" => "static#feed"
  match "/(:page)" => "facts#index", :as => :root
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :fact
  belongs_to :user

  validates_presence_of :text
  validates_presence_of :fact
  validates_presence_of :user
end

app/controllers/comments_controller.rb
# -*- encoding: utf-8 -*-
class CommentsController < ApplicationController
  load_and_authorize_resource

  def create
    @comment = Comment.new(params[:comment])
    @fact = Fact.find_by_title_url!(params[:fact_id])
    @comment.fact = @fact
    @comment.user = current_user

    flash[:notice] = "Gràcies per comentar!"

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @fact }
        format.js
      else
        redirect_to(@fact)
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.user == current_user || @comment.fact.user == current_user
      @comment.destroy
    end

    respond_to do |format|
      format.html { redirect_to @comment.fact }
      format.js
    end
  end
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/views/comments/_comment.html.haml
.comment{:id => "comment_#{comment.id}"}
  %hr
  .gravatar= gravatar_image_tag(comment.user.email)
  .delete
    - if can? :destroy, comment
      = button_to 'Elimina', fact_comment_path(@fact, comment), :confirm => "N'estas segur?", :method => :delete, :remote => true, :class => "button" |
  .metadata
    %h3= comment.user.name
    .sent Enviat fa #{time_ago_in_words(comment.created_at)}
  .text= to_md comment.text

app/views/comments/create.js.erb
/* Insert a notice between the last comment and the comment form */
var ts = new Date().getTime();
$("#comment-notice").html('<div id='+ts+' class="flash"><%= escape_javascript(flash.delete(:notice)) %></div>');
$("#"+ts+".flash").purr();

/* Replace the count of comments */
$("#comments").html("<%= @comment.fact.comments.count %>");
$("#comments-count").html("<%= pluralize(@comment.fact.comments.count, 'comentari') %>");

/* Add the new comment to the bottom of the comments list */
$("#comment-list").append("<%= escape_javascript(render(@comment)) %>");

/* Highlight the new comment */
$("#comment_<%= @comment.id %>").effect("highlight", {}, 3000);

/* Reset the comment form */
$("#new_comment")[0].reset();

app/views/comments/destroy.js.erb
/* Eliminate the comment by fading it out */
$('#comment_<%= @comment.id %>').fadeOut();
/* Replace the count of comments */
$("#comments").html("<%= @comment.fact.comments.count %>");
$("#comments-count").html("<%= pluralize(@comment.fact.comments.count, 'comentari') %>");