config/routes.rb
KnowledgeBase::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => 'registrations', :sessions => "sessions"}

  # Administration
  namespace :admin do
    resources :facts, :only => [:index, :update, :destroy]
    resources :categories, :only => [:index, :create, :update, :destroy]

    root :to => "overview#index"
  end

  resources :facts, :except => :index do
    get :autocomplete_tag_name, :on => :collection
    resources :comments
  end

  resources :tags, :only => [:create, :destroy] do
    collection do
      get 'add'
    end
  end

  resources :authentications, :only => :destroy
  match '/auth/:provider/callback' => 'authentications#create'

  match "/feed" => "static#feed"
  match "/(:page)" => "facts#index", :as => :root
end

app/views/shared/_admin_header.html.haml
#header
  #preheader
    #center-preheader Panell d'administració (#{link_to "Sortir", destroy_user_session_path})
    #right-preheader= link_to "Tornar a #{APP_CONFIG['hostname']} ->", root_url
  .inner
    #menu
      %ul
        %li= link_to "Entrades", admin_facts_path
        %li= link_to "Categories", admin_categories_path

app/views/shared/_flash.html.haml
- flash = {} unless flash
- flash[:notice] = notice if notice
- flash[:alert] = alert if alert
- if flash
  - flash.each do |msg|
    .flash= msg[1]

app/views/shared/_header.html.haml
-# Calculate name and mail
- name = current_user ? current_user.name : "Desconegut"
- email = current_user ? current_user.email : ""
- user_key = current_user ? email : "-"
- user_upd = current_user ? current_user.updated_at : "-"
- cache "header_lang_#{I18n.locale}_user_#{user_key}_at_#{user_upd}" do
  #header
    #left
      = link_to "http://itnig.net", :id => "img" do
        = image_tag "intranet_50.png", :alt => "Logo Itnig Intranet"
      = link_to root_path, :id => "title" do
        Knowledge Base
      #social
        .facebook
          %script{:src => "http://connect.facebook.net/ca_ES/all.js#xfbml=1"}
          %fb:like{:href => APP_CONFIG["hostname"], :layout => "button_count", :show_faces => "true"}
        .twitter
          = tweet_button(:via => "itnig", :url => "http://#{APP_CONFIG["hostname"]}", :text => "Checkout the awesome Knowledge Base!", :count => "horizontal")
        .google
          %script{:type => "text/javascript", :src => "https://apis.google.com/js/plusone.js"}
            {lang: 'ca'}
          %g:plusone{:size => "medium"}
    #right
      -# Render
      %p= name
      %ul
        %li= link_to "Entrades", root_path
        |
        - if current_user
          %li= link_to "Nova entrada", new_fact_path
          |
          %li= link_to "Preferències", edit_user_registration_path
          |
          - if current_user.admin?
            %li= link_to "Backoffice", admin_root_path
            |
          %li= link_to "Sortir", destroy_user_session_path
          |
        - else
          %li= link_to "Entrar", new_user_session_path
          |
        %li
          = link_to "http://feeds.feedburner.com/itnig/knowledge" do
            = image_tag "rss-header.png"
      = gravatar_image_tag(email, :class => "pic", :gravatar => {:size => 65})
  - unless current_user
    #notconnected
      No has entrat com a usuari. Pots #{ link_to "registrar-te", new_user_registration_path} o #{ link_to "entrar", new_user_session_path}. Així podràs crear entrades o comentar-ne d'altres!

app/views/shared/_itnig_header.html.haml
#itnig-header
  #nav
    %ul
      %li
        = link_to 'Itnig', "http://itnig.net/en"
      %li
        = link_to 'Service', "http://itnig.net/en/service"
      %li
        = link_to 'Company', "http://itnig.net/en/company"
      %li
        = link_to 'Projects', "http://itnig.net/en/projects"
      %li
        = link_to 'Events', "http://itnig.net/en/events"
      -#%li.nav-blog
        = section_link_to 'Blog', posts_path
      %li
        = link_to 'Knowledge', 'http://how.itnig.net', :class => "current"
      %li.nav-contact
        =link_to 'Contact','http://itnig.net/en#footer-container'
      .clear
.clear