config/routes.rb
KnowledgeBase::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => 'registrations', :sessions => "sessions"}

  # Administration
  namespace :admin do
    resources :facts, :only => [:index, :update, :destroy]
    resources :categories, :only => [:index, :create, :update, :destroy]

    root :to => "overview#index"
  end

  resources :facts, :except => :index do
    get :autocomplete_tag_name, :on => :collection
    resources :comments
  end

  resources :tags, :only => [:create, :destroy] do
    collection do
      get 'add'
    end
  end

  resources :authentications, :only => :destroy
  match '/auth/:provider/callback' => 'authentications#create'

  match "/feed" => "static#feed"
  match "/(:page)" => "facts#index", :as => :root
end

app/models/fact.rb
# -*- encoding: utf-8 -*-
class Fact < ActiveRecord::Base
  CATEGORIES = ["Enginyeria","Màrqueting","Disseny"]

  validates :title,  :presence => true
  validates_uniqueness_of :title
  validates :description, :presence => true,
                    :length => { :minimum => 5 }
  validates_presence_of :user
  validates_presence_of :category

  has_many :fact_tags
  has_many :tags, :through => :fact_tags
  has_many :comments
  belongs_to :user
  belongs_to :category

  before_save :calculate_title_url

  default_scope order("created_at DESC")

  # All facts for that tag (remember a tag name is unique)
  scope :for_tag, lambda {|tag_name| joins(:tags).where(:tags => {:name => tag_name}) }

  # All facts for that user name (remember a user name is also unique!)
  scope :for_user, lambda {|user_name| joins(:user).where(:users => {:name => user_name}) }

  # All facts filtered by one or more categories
  scope :for_category, lambda {|category_name| joins(:category).where(:categories => {:name => category_name}) }
  scope :for_categories, lambda {|categories| where(:category_id => categories) }

  def to_s
    title
  end

  def to_param
    title_url
  end

  def calculate_title_url
    self.title_url = title.downcase.to_ascii.gsub(/[^[:alnum:]]/,'-')
  end

  # Sphinx
  define_index do
    # fields
    indexes title
    indexes title_url
    indexes description
    indexes user.name
    indexes user.email
    indexes tags.name
    indexes category.name

    # attributes
    has created_at

    # delta indexing
    set_property :delta => true
  end
end

app/controllers/admin/facts_controller.rb
class Admin::FactsController < Admin::AdminController
  def index
    @page = params[:page] || 1
    @facts = Fact.includes(:user).all.paginate :page => @page, :per_page => 20
    @categories = Category.all
  end

  def update
    @fact = Fact.find_by_title_url!(params[:id])
    @fact.update_attributes(params[:fact])

    respond_to do |format|
      format.html { redirect_to admin_categories_path }
      format.json { head :ok }
    end
  end

  def destroy
    @fact = Fact.find_by_title_url!(params[:id])
    @fact.destroy
    redirect_to admin_facts_path
  end
end

app/controllers/facts_controller.rb
# -*- encoding: utf-8 -*-
class FactsController < ApplicationController
  autocomplete :tag, :name, :full => true

  before_filter :show_find, :only => :show
  before_filter :edit_find, :only => :edit
  load_resource :find_by => :title_url
  authorize_resource

  def index
    # Search params
    @is_search = params[:search]
    @page = params[:page].to_i
    @page = 1 if @page == 0

    if @is_search
      # Search directly
      @facts = Fact.search(params[:search], :order => :created_at, :sort_mode => :desc, :include => [:user,:comments,:tags,:category], :page => @page, :per_page => 10)
    else
      # Get base
      @base = Fact.includes(:user,:comments,:tags,:category)
      @base = @base.for_categories(current_user.categories) if user_signed_in?

      # Get total
      if @tag = params[:tag]
        @total = @base.for_tag(@tag)
        @noindex = true # SEO purposes. Tell the robots not to index in this case.
      elsif @category = params[:category]
        @total = @base.for_category(@category)
      elsif @user = params[:user]
        @total = @base.for_user(@user)
      else
        @total = @base
      end

      @facts = @total.paginate :page => @page, :per_page => 10
    end
  end

  def show
  end

  def new
    @fact = Fact.new
    @tags = Tag.includes(:fact_tags)
    @categories = Category.all
  end

  def create
    @fact = Fact.new(params[:fact])
    @fact.user = current_user

    if @fact.save
      @fact.reload
      redirect_to(root_path, :notice => "L'entrada ha estat creada satisfactòriament")
    else
      @tags = Tag.all
      @categories = Category.all
      flash[:alert] = "Assegura't d'introduir el títol (ha de ser únic!) i el text abans de crear l'entrada, siusplau"
      render :action => "new"
    end
  end

  def edit
    @tags = Tag.all
    @categories = Category.all
  end

  def update
    @fact = Fact.find_by_title_url!(params[:id])

    if @fact.update_attributes(params[:fact])
      redirect_to(root_path, :notice => "L'entrada ha estat actualitzada satisfactòriament")
    else
      @tags = Tag.all
      @categories = Category.all
      flash[:alert] = "Assegura't d'introduir el títol i el text abans d'actualitzar l'entrada, siusplau"
      render :action => "edit"
    end
  end

  def destroy
    @fact = Fact.find_by_title_url!(params[:id])
    if @fact.destroy
      flash[:notice] = "L'entrada s'ha eliminat satisfactòriament"
    else
      flash[:alert] = "No pots eliminar una entrada que no sigui teva"
    end

    redirect_to root_path
  end

  private

  def show_find
    @fact = Fact.includes(:user,[:comments => [:user,:fact]]).find_by_title_url!(params[:id])
  end

  def edit_find
    @fact = Fact.includes(:fact_tags).find_by_title_url!(params[:id])
  end
end

app/helpers/facts_helper.rb
module FactsHelper
end

app/views/facts/_comments.html.haml
#comments
  %h3
    #comments-count= pluralize(comments.count, "comentari")
  %ul#comment-list
    - comments.each do |comment|
      = render "comments/comment", :comment => comment
  #comment-notice
  - if can? :create, fact
    %h4 #{current_user.name}, deixa un comentari!
    #newcomment
      #gravatar= gravatar_image_tag(current_user.email)
      .tip Aquest text es formatarà amb #{link_to 'Markdown', "http://daringfireball.net/projects/markdown/syntax", { :target => "_new" }}. A més, pots assenyalar codi envoltant-lo de "```".
      = simple_form_for [fact, Comment.new], :remote => true do |f|
        = f.text_area :text, :id => "newcomment-area"
        = f.submit "Envia", :id => "newcomment-button", :class => "button"

app/views/facts/_form.html.haml
#fact-form
  = simple_form_for @fact, :html => { :id => "fact_form" } do |f|
    -# HEADER
    - user = @fact.new_record? ? current_user : @fact.user
    = gravatar_image_tag(user.email, :class => "plus")
    = f.text_field :title
    #metadata
      - unless @fact.new_record?
        -# metadata
    %hr

    -# DESCRIPTION
    Aquest text es formatarà amb #{link_to 'Markdown', "http://daringfireball.net/projects/markdown/syntax", { :target => "_new" }}. A més, pots assenyalar codi envoltant-lo de "```".
    %br
    = f.text_area :description, :id => "description_area", :class => "elastic"

    %hr

    -# CATEGORY
    #category
      %h3 Categoria
      #category_picker= f.association :category, :as => :radio, :collection => @categories.map{|c|[c.id,c.name]}, :label_method => :last, :value_method => :first, :label => false

    -# TAGS
    %br
    #tags
      %h3 Etiquetes
      #tag_inputs
        -# The real thing will be held here inside!
      #new_tag
        = text_field_tag :tag_name, "Introdueix etiqueta...", "data-autocomplete" => autocomplete_tag_name_facts_path
      #tag_cloud
        - @fact.tags.each do |tag|
          = render "tags/form_tag", :tag => tag

    -# LINKS
    = f.submit (@fact.new_record? ? "Crear entrada" : "Actualitzar entrada")
    %br

- content_for :custom_js do
  :javascript
    // Label to show when nothing is written there
    var blank_label = "Introdueix etiqueta..."

    // Functions

    // Add the tag
    function addTag(){
      // Get name and delete it from input
      var tagInput = $("#tag_name");
      var tagName = tagInput.val();
      tagInput.val("");

      // Add if not binded yet
      if(!tagExists(tagName)){
        $.ajax({
          url: "/tags/add",
          data: { name : tagName }
        });
      }
    }

    function tagExists(tagName){
      var isThis = false;
      $("#tag_cloud > .tag > .name").each(function(){
        var thisTagName = $(this).html();
        if(tagName == thisTagName){
          isThis = true;
          return false;
        }
      });
      return isThis;
    }

    $(document).ready(function() {
      // Cross-site request forgery params
      var csrf_token = $('meta[name=csrf-token]').attr('content');
      var csrf_param = $('meta[name=csrf-param]').attr('content');

      // Delete tag class management
      $(".tag").live('hover', function() {
        $(this).find(".delete-tag").show();
      });
      $(".tag").live('mouseleave', function() {
        $(this).find(".delete-tag").hide();
      })

      // Focus out on tag form
      $("#tag_name").focusout(function() {
        if ($(this).val() == "") {
          $(this).val(blank_label);
          $(this).css("color", "#AAA");
        }
      });

      // Focus on tag form
      $("#tag_name").focus(function() {
        var tag_input = $(this);
        if ($(this).val() == blank_label) {
          $(this).val("");
        }
      });

      // Keydown on tag form
      $("#tag_name").keydown(function(e) {
        if (e.keyCode == 13){
          e.preventDefault();
          e.stopPropagation();
        }
      });

      // Keyup on tag form
      $("#tag_name").keyup(function(e) {
        e.preventDefault();
        if (e.keyCode == 13) {
          var tag_input = $(this);
          var tag_name = tag_input.val();
          if (tag_name != ""){
            var data = "_method=post";
            data += "&tag[name]=" + encodeURIComponent(tag_name);
            if (csrf_param !== undefined && csrf_token !== undefined) {
              data += "&" + csrf_param + "=" + encodeURIComponent(csrf_token);
            }
            var options = {};
            options.type = "post";
            options.dataType = "script";
            options.data = data;
            options.url = "/tags";
            options.beforeSend = function(xhr){ xhr.setRequestHeader("Accept", "text/javascript"); }
            var ajaxRequest = jQuery.ajax(options);
          }
        }
      });

      // Click on autocomplete
      $('#tag_name').bind('railsAutocomplete.select', function(){
        addTag();
      });

      // Unbinding tag from the fact
      $(".delete-tag > a").live("click", function() {
        if (confirm("¿N'estas segur?")) {
          $(this).parent().parent().remove();
        }
      });

      // Gather selected tags and send them
      $("#fact_submit").click(function(e) {
        var tag_inputs = "";
        var i = 0;
        $(".tag > .delete-tag > a").each(function() {
          tag_inputs += "<input id='fact_tag_ids_" + $(this).attr("data_tag");
          tag_inputs += "' name='fact[tag_ids][]' type='hidden' value='";
          tag_inputs += $(this).attr("data_tag");
          tag_inputs += "'>";
          i++;
        });
        if(i==0)
          tag_inputs = "<input name='fact[tag_ids][]' type='hidden' value=''>";
        $("#tag_inputs").html(tag_inputs);
        $("#fact_submit").submit();
      });
    });

app/views/facts/_tags.html.haml
#tags
  %h3 Tags
  - tags.each do |tag|
    .tag= link_to tag.name, root_path(:tag => tag.name)
  .clear

app/views/facts/edit.html.haml
- content_for :custom_title do
  = "Edició d'una entrada"
%h2 Edició d'una entrada
= render "form"

app/views/facts/index.html.haml
-# get title, to be used both in the page title and as H2
- if @is_search
  - title = "Resultats de cerca"
- else
  - if @tag
    - title = "Entrades del tag '#{@tag.capitalize}'"
  - elsif @category
    - title = "Entrades de la categoria '#{@category.capitalize}'"
  - elsif @user
    - title = "Entrades de l'usuari '#{@user}'"
  - else
    - title = "Llista d'entrades"

- content_for :custom_title do
  = title

- user_key = current_user ? current_user.email : "-"

#fact-list
  %h2= title
  #search-bar
    = form_tag root_path, :method => "get" do
      = text_field_tag :search, @is_search || "Cerca aquí..."
    = link_to "javascript:doSearch();" do
      = image_tag "magnifier-search.png"
  #pagination= will_paginate @facts, :previous_label => "← Anterior", :next_label => "Següent →"
  - if @facts.empty?
    No hi ha entrades.
  - @facts.each do |fact|
    - cache "fact-at-index_lang_#{I18n.locale}_fact_#{fact.id}_at_#{fact.updated_at}_for_#{user_key}" do
      %hr
      .fact
        = link_to root_path(:user => fact.user.name) do
          = gravatar_image_tag(fact.user.email)
        = link_to fact_path(fact, :anchor => "comments"), :class => "comments-link" do
          .comments-wrapper
            - nc = fact.comments.size
            - nc = "#{99}+" if nc > 99
            .comments= nc
        - if fact.category.present?
          .category= link_to fact.category, root_path(:category => fact.category.name)
        .metadata
          = link_to fact do
            %h3= fact.title
          .dates
            Creat
            = cached_timestamp(fact.created_at)
            per
            = get_name_or_you(fact.user)
            - if fact.created_at != fact.updated_at
              | Actualitzat per últim cop
              = cached_timestamp(fact.updated_at)
        .text= to_md(fact.description, :length => 600)
        .tags
          - fact.tags.each do |tag|
            .tag= link_to tag, root_path(:tag => tag.name)

- content_for :custom_js do
  :javascript
    $("#search").focus(function(){
      if ($(this).val()=="Cerca aquí..."){
        $(this).val("");
      }
    });

    $("#search").blur(function(){
      if ($(this).val()==""){
        $(this).val("Cerca aquí...");
      }
    });

app/views/facts/new.html.haml
- content_for :custom_title do
  = "Nova entrada"
%h2 Nova entrada
= render 'form'

app/views/facts/show.html.haml
- content_for :custom_title do
  = @fact.title

- user_key = current_user ? current_user.email : "-"
- cache "fact-show_lang_#{I18n.locale}_fact_#{@fact.id}_at_#{@fact.updated_at}_for_#{user_key}" do
  #fact-show
    #gravatar= gravatar_image_tag(@fact.user.email)
    = link_to "#comments" do
      #comments-wrapper
        - nc = @fact.comments.size
        - nc = "#{99}+" if nc > 99
        #comments= nc
    - if @fact.category.present?
      #category= link_to @fact.category, root_path(:category => @fact.category.name)
    #links
      - if can? :edit, @fact
        = button_to 'Edita', edit_fact_path(@fact), :method => :get, :class => "button"
      - if can? :destroy, @fact
        = button_to 'Elimina', fact_path(@fact), :confirm => "Are you sure?", :method => :delete, :class => "button" |
    #head
      %h2= @fact.title
      #metadata
        Creat
        = cached_timestamp(@fact.created_at)
        per
        = link_to get_name_or_you(@fact.user), root_path(:user => @fact.user.name)
        - if @fact.created_at != @fact.updated_at
          | Actualitzat per últim cop
          = cached_timestamp(@fact.updated_at)
      #social
        .facebook
          %script{:src => "http://connect.facebook.net/ca_ES/all.js#xfbml=1"}
          %fb:like{:href => request.url, :layout => "button_count", :show_faces => "true"}
        .twitter
          = tweet_button(:via => "itnig", :url => request.url, :text => "Checkout the awesome Knowledge Base!", :count => "horizontal")
        .google
          %script{:type => "text/javascript", :src => "https://apis.google.com/js/plusone.js"}
            {lang: 'ca'}
          %g:plusone{:size => "medium"}
    #text
      = to_md @fact.description
    %hr
    = render "tags", :tags => @fact.tags
    %hr
    = render "comments", :comments => @fact.comments, :fact => @fact