config/routes.rb
KnowledgeBase::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => 'registrations', :sessions => "sessions"}

  # Administration
  namespace :admin do
    resources :facts, :only => [:index, :update, :destroy]
    resources :categories, :only => [:index, :create, :update, :destroy]

    root :to => "overview#index"
  end

  resources :facts, :except => :index do
    get :autocomplete_tag_name, :on => :collection
    resources :comments
  end

  resources :tags, :only => [:create, :destroy] do
    collection do
      get 'add'
    end
  end

  resources :authentications, :only => :destroy
  match '/auth/:provider/callback' => 'authentications#create'

  match "/feed" => "static#feed"
  match "/(:page)" => "facts#index", :as => :root
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :facts
  has_many :user_categories
  has_many :users, :through => :users

  validates_presence_of :name
  validates_uniqueness_of :name

  def to_s
    name
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminController
  def index
    @categories = Category.all
    @uncategorized_count = Fact.where(:category_id => 0).count
  end

  def create
    @category = Category.new(params[:category])
    @category.save
    redirect_to admin_categories_path
  end

  def update
    @category = Category.find(params[:id])
    @category.update_attributes(params[:category])

    respond_to do |format|
      format.html { redirect_to admin_categories_path }
      format.json { head :ok }
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to admin_categories_path
  end
end

app/views/admin/categories/index.html.haml
%h1 Llistat de categories
= link_to "Crear una categoria", "#create_category", :rel => "facebox[.create_category]"
%table
  %tr
    %th Nom
    %th Entrades
    %th
  - @categories.each do |category|
    %tr
      %td= best_in_place category, :name, :type => :input, :path => admin_category_path(category)
      %td= category.facts.count
      %td= button_to "Eliminar", admin_category_path(category), :method => :delete, :confirm => "N'estas segur?"
  %tr
    %td Sense categoria
    %td= @uncategorized_count
    %td

#create_category{:style => "display: none;"}
  %h2 Nova categoria
  = simple_form_for [:admin, Category.new] do |f|
    = f.input :name, :label => "Nom"
    = f.submit "Crear"